"use client";

import { useMemo } from "react";

export type CatAnimationState = "idle" | "walk";

interface CatProps {
  /** Cat key, matches sprite file at /public/cats/{catId}.png */
  catId: string;
  /** Animation to play. Sheets are 8-frame walk cycles. */
  state?: CatAnimationState;
  /** Rendered square size in px. */
  size?: number;
  /** Render as a locked silhouette teaser. */
  locked?: boolean;
  /** Flip horizontally (face left). */
  flip?: boolean;
  className?: string;
}

const FRAMES = 8;

/**
 * Sprite-sheet cat. Each cat is one horizontal 8-frame PNG.
 * `walk` steps through all frames; `idle` holds frame 0 with a gentle float.
 * Sprite assets are generated by scripts/gen-cat-sprites.mjs.
 */
export default function Cat({
  catId,
  state = "idle",
  size = 80,
  locked = false,
  flip = false,
  className = "",
}: CatProps) {
  const style = useMemo<React.CSSProperties>(() => {
    const sheetW = size * FRAMES;
    return {
      width: size,
      height: size,
      backgroundImage: `url(/cats/${catId}.png)`,
      backgroundRepeat: "no-repeat",
      backgroundSize: `${sheetW}px ${size}px`,
      ["--cat-sheet-w" as string]: `${sheetW}px`,
      imageRendering: "auto",
      filter: locked ? "grayscale(1) brightness(0.55) opacity(0.7)" : undefined,
      transform: flip ? "scaleX(-1)" : undefined,
    };
  }, [catId, size, locked, flip]);

  const animClass =
    state === "walk" ? "animate-cat-sprite-walk" : "animate-cat-idle";

  return (
    <div
      role="img"
      aria-label={`cat-${catId}`}
      className={`${animClass} ${className}`}
      style={style}
    />
  );
}
